# workflow to enforce style and linting on PR
name: eslint-prettier
on:
  pull_request:
    branches:
      - main
jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # Setup bun environment to run tests
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - run: bun install --frozen-lockfile # equivalent to npm ci
      - run: bun run lint:eslint-config-prettier
      - run: bun run format
      - run: bun run lint
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier formatting changes and check with eslint
